# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LixAgents < Formula
  desc "CLI tool for obtaining temporary Lix API tokens with email-based approval"
  homepage "https://github.com/lix-it/lix-agents"
  version "0.2.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lix-it/lix-agents/releases/download/v0.2.0/lix-agents_0.2.0_darwin_amd64.tar.gz"
      sha256 "ee4d4ebaa823aa5cd52c7cb07ffe6cc71785ea2e7373bd562a084339d79a0105"

      define_method(:install) do
        bin.install "lix-agents"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lix-it/lix-agents/releases/download/v0.2.0/lix-agents_0.2.0_darwin_arm64.tar.gz"
      sha256 "cfd37d14a1e40b27254fecc78d6ffdc81256141b72e51fbd7260f34356725be2"

      define_method(:install) do
        bin.install "lix-agents"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/lix-it/lix-agents/releases/download/v0.2.0/lix-agents_0.2.0_linux_amd64.tar.gz"
      sha256 "606468ed682bc28d57838e4ef8784d690817abf1c0ea855fa47b1c3fda14132d"
      define_method(:install) do
        bin.install "lix-agents"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lix-it/lix-agents/releases/download/v0.2.0/lix-agents_0.2.0_linux_arm64.tar.gz"
      sha256 "11d3b6900ad1545ed7150920139e64e9d98ac77eace171e291b835d1d0e5b57f"
      define_method(:install) do
        bin.install "lix-agents"
      end
    end
  end

  test do
    system "#{bin}/lix-agents", "--help"
  end
end
